'use strict';
/**
 * zipBuilder.js – Assembles the downloaded HTML + assets into a ZIP file.
 *
 * Creates a well-structured archive:
 *
 *   <site-hostname>/
 *   ├── index.html
 *   ├── assets/
 *   │   ├── css/
 *   │   ├── js/
 *   │   ├── images/
 *   │   └── fonts/
 *   └── manifest.json   (metadata about the crawl)
 *
 * The archive is streamed directly to the response (no tmp file needed),
 * OR written to a tmp file path if a dest path is provided.
 */

const archiver = require('archiver');
const fs = require('fs');
const path = require('path');
const { URL } = require('url');

/**
 * Builds a ZIP archive from the crawl results.
 *
 * @param {object}              opts
 * @param {string}              opts.html        – Rewritten HTML string
 * @param {Map<string,Buffer>}  opts.fileMap     – localPath → Buffer
 * @param {string}              opts.pageUrl     – Original crawled URL
 * @param {string}              [opts.destPath]  – File path to write ZIP to (optional)
 * @param {import('stream').Writable} [opts.outputStream] – Stream to pipe into (optional)
 * @returns {Promise<{ zipPath?: string, size: number }>}
 */
async function buildZip({ html, fileMap, pageUrl, destPath, outputStream }) {
  const hostname = (() => { try { return new URL(pageUrl).hostname; } catch { return 'site'; } })();
  const rootDir = hostname.replace(/[^a-z0-9.-]/gi, '_');

  // Create archiver instance with maximum compression
  const archive = archiver('zip', {
    zlib: { level: 6 }, // balance between speed and compression
  });

  // Set up the output destination
  let writeStream;
  if (outputStream) {
    writeStream = outputStream;
  } else if (destPath) {
    writeStream = fs.createWriteStream(destPath);
  } else {
    throw new Error('zipBuilder: must provide either destPath or outputStream');
  }

  const finishPromise = new Promise((resolve, reject) => {
    let bytesWritten = 0;
    archive.on('data', (chunk) => { bytesWritten += chunk.length; });

    // For file streams, we MUST wait for 'finish' to ensure OS flush
    // For other streams, 'end' is usually sufficient
    writeStream.on('finish', () => resolve(bytesWritten));
    archive.on('end', () => {
      if (outputStream) resolve(bytesWritten);
    });

    archive.on('error', reject);
    writeStream.on('error', reject);
  });

  archive.pipe(writeStream);

  // ── index.html ──
  archive.append(Buffer.from(html, 'utf-8'), {
    name: `${rootDir}/index.html`,
    date: new Date(),
  });

  // ── Assets ──
  for (const [localPath, buffer] of fileMap.entries()) {
    archive.append(buffer, {
      name: `${rootDir}/${localPath}`,
      date: new Date(),
    });
  }

  // ── manifest.json ── (metadata about the crawl)
  const manifest = {
    url: pageUrl,
    crawledAt: new Date().toISOString(),
    assets: fileMap.size,
    rootDir,
    generator: 'website-to-zip v1.0.0',
  };
  archive.append(JSON.stringify(manifest, null, 2), {
    name: `${rootDir}/manifest.json`,
  });

  // ── README.txt ──
  const readme = [
    `Website Archive`,
    `===============`,
    `URL:        ${pageUrl}`,
    `Crawled at: ${manifest.crawledAt}`,
    `Assets:     ${fileMap.size}`,
    ``,
    `Open index.html in your browser to view the archived site.`,
    ``,
    `Generated by website-to-zip (https://github.com/you/website-to-zip)`,
  ].join('\n');
  archive.append(readme, { name: `${rootDir}/README.txt` });

  // Finalize the archive (flush all buffers)
  await archive.finalize();

  const size = await finishPromise;
  return { zipPath: destPath, size };
}

async function cleanupDir(dirPath) {
  try {
    if (fs.existsSync(dirPath)) {
      await fs.promises.rm(dirPath, { recursive: true, force: true });
    }
  } catch (err) {
    console.warn(`[zipBuilder] Failed to cleanup ${dirPath}: ${err.message}`);
  }
}

module.exports = { buildZip, cleanupDir };
